language: node_js

node_js:
  - "12"

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.19.1
  - export PATH=$HOME/.yarn/bin:$PATH
  - yarn
  - yarn run build

cache:
  directories:
    - $HOME/.yarn