language: node_js

node_js:
  - "12"

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- -- --version $(grep 'yarn' package.json | cut -d '"' -f4)
  - export PATH=$HOME/.yarn/bin:$PATH

before_script:
  - yarn run build

cache:
  directories:
    - $HOME/.yarn

script:
  - node_modules/.bin/eslint src/**/*.ts
  - yarn test